# these values are either updated by the simulation environment or by Vicon
controller:
  obstacles:
    dynamic:
      -
        name: projectile1
        # NOTE: these are *initial conditions*. In real experiment, the
        # position is relative to the origin of the world frame. In simulation,
        # position and velocity are (typically) (re-)set by the simulator for
        # maximum accuracy.
        radius: 0.2
        modes:
          -
            time: 0
            position: [0, -10, 0]  # out of the way
            velocity: [0, 0, 0]
            acceleration: [0, 0, -9.81]

    collision_pairs:
      # wrist, forearm, and shoulder
      - ["wrist1_collision_link_0", "shoulder_collision_link_0"]
      # - ["wrist1_collision_link_0", "upper_arm_collision_link1_0"]
      - ["wrist3_collision_link_0", "shoulder_collision_link_0"]
      - ["forearm_collision_sphere_link2_0", "shoulder_collision_link_0"]

      - ["forearm_collision_sphere_link2_0", "balanced_object_collision_link_0"]

      # wrist and ground
      - ["wrist3_collision_link_0", "ground"]

      # arm and dynamic obstacles
      # - ["balanced_object_collision_link_0", "projectile1"]
      # - ["wrist3_collision_link_0", "projectile1"]
      # - ["wrist1_collision_link_0", "projectile1"]
      # - ["forearm_collision_sphere_link2_0", "projectile1"]
      # - ["forearm_collision_sphere_link1_0", "projectile1"]

simulation:
  dynamic_obstacles:
    obstacles:
      -
        # True if the object's trajectory should be tracked, false if it should
        # just be allowed to evolve subject to gravity
        # Note that acceleration is still required either way
        controlled: false
        radius: 0.1
        relative: true
        modes:
          -
            time: 0
            position: [0.0, -2.0, 0.3]  # relative to EE if relative=true
            velocity: [0, 2.67, 3.68]
            acceleration: [0, 0, -9.81]
          -
            time: 2
            position: [1.414, -1.414, 0]
            velocity: [-1.89, 1.89, 3.68]
            acceleration: [0, 0, -9.81]
          -
            time: 4
            position: [2.0, 0, 0]
            velocity: [-2.67, 0, 3.68]
            acceleration: [0, 0, -9.81]
          -
            time: 6
            position: [1.414, 1.414, 0]
            velocity: [-1.89, -1.89, 3.68]
            acceleration: [0, 0, -9.81]
          -
            time: 8
            position: [0, 2.0, 0]
            velocity: [0, -2.67, 3.68]
            acceleration: [0, 0, -9.81]
