simulation:
  robot:
    # home: [0, 0, 0, 0.5pi, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]  # upright
    home: [-1, 1, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 27 # state
      u: 9  # input
    noise:
      measurement:
        q_std_dev: 0
        v_std_dev: 0
      process:
        v_std_dev: 0
    joint_names:
      - "x_to_world_joint"
      - "y_to_x_joint"
      - "base_to_y_joint"
      - "ur10_arm_shoulder_pan_joint"
      - "ur10_arm_shoulder_lift_joint"
      - "ur10_arm_elbow_joint"
      - "ur10_arm_wrist_1_joint"
      - "ur10_arm_wrist_2_joint"
      - "ur10_arm_wrist_3_joint"
    tool_joint_name: "gripped_object_joint"
    base_type: omnidirectional
    urdf:
      package: "upright_assets"
      path: "thing/urdf/thing_pyb.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/cartesian_base_joints.urdf.xacro"
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/collision_links.urdf.xacro"
      args:
        use_collision: "false"
        transform_params: "$(find upright_cmd)/config/robots/calibration/tray_transforms_real.yaml"
        show_balance_link: "false"

controller:
  # robot parameters
  robot:
    dims:
      q: 9  # generalized position
      v: 9  # generalized velocity
      x: 27 # state
      u: 9  # input
    x0: [-1, 1, 0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi, 0rep9, 0rep9] #0rep9是9个0的意思
    urdf:
      package: "upright_assets"
      path: "thing/urdf/thing_ocs2.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/collision_links.urdf.xacro"
      args:
        use_collision: "true"
        transform_params: "$(find upright_cmd)/config/robots/calibration/tray_transforms_real.yaml"
    tool_link_name: "gripped_object"
    base_type: omnidirectional

  # weights on state, input, and end effector pose
  weights:
    input:
      scale: 0.001
      diag: [1rep9]
    state:
      scale: 0.01
      diag: [0rep9, 10rep9, 1rep9]
    end_effector:
      scale: 1
      diag: [1, 1, 1, 0, 0, 0]

  # state and input limits
  limits:
    constraint_type: hard
    input:
      lower: [-20, -20, -20, -80, -80, -80, -80, -80, -80]
      upper: [20, 20, 20, 80, 80, 80, 80, 80, 80]
    state:
      lower: [-10, -10, -10, -2pi, -2pi, -2pi, -2pi, -2pi, -2pi,
              -1.1, -1.1, -2, -2, -2, -3, -3, -3, -3,
              -2.5, -2.5, -1, -10, -10, -10, -10, -10, -10]
      upper: [10, 10, 10, 2pi, 2pi, 2pi, 2pi, 2pi, 2pi,
              1.1, 1.1, 2, 2, 2, 3, 3, 3, 3,
              2.5, 2.5, 1, 10, 10, 10, 10, 10, 10]
