simulation:
  robot:
    # home: [0.5pi, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi]  # upright
    home: [0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi]  # standard
    # home: [0.5pi, -0.25pi, 0, 0.25pi, 0.5pi, -0.583pi]  # inverted
    dims:
      q: 6  # generalized position
      v: 6  # generalized velocity
      x: 18 # state
      u: 6  # input
    noise:
      measurement:
        q_std_dev: 0
        v_std_dev: 0
      process:
        v_std_dev: 0
    joint_names:
      - "ur10_arm_shoulder_pan_joint"
      - "ur10_arm_shoulder_lift_joint"
      - "ur10_arm_elbow_joint"
      - "ur10_arm_wrist_1_joint"
      - "ur10_arm_wrist_2_joint"
      - "ur10_arm_wrist_3_joint"
    locked_joints:
      x_to_world_joint: -1.0
      y_to_x_joint: 1.0
      base_to_y_joint: 0
    tool_joint_name: "gripped_object_joint"
    base_type: fixed
    urdf:
      package: "upright_assets"
      path: "thing/urdf/thing_pyb.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/cartesian_base_joints.urdf.xacro"
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/collision_links.urdf.xacro"
      args:
        use_collision: "false"
        transform_params: "$(find upright_cmd)/config/robots/calibration/tray_transforms_real.yaml"
        show_balance_link: "false"

controller:
  # robot parameters
  robot:
    dims:
      q: 6  # generalized position
      v: 6  # generalized velocity
      x: 18 # state
      u: 6  # input
    # x0: [0.5pi, -0.75pi, -0.5pi, -0.25pi, -0.5pi, 0.5pi, 0rep6, 0rep6]  # upright
    x0: [0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi, 0rep6, 0rep6]  # standard
    # x0: [0.5pi, -0.25pi, 0, 0.25pi, 0.5pi, -0.583pi, 0rep6, 0rep6]  # inverted
    base_pose: [-1.0, 1, 0]  # planar: x, y, Î¸
    urdf:
      package: "upright_assets"
      path: "thing/urdf/thing_ocs2.urdf"
      includes:
        - "$(find mobile_manipulation_central)/urdf/xacro/thing_no_wheels.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/end_effectors/gripped_object.urdf.xacro"
        - "$(find upright_assets)/thing/xacro/collision_links.urdf.xacro"
      args:
        use_collision: "true"
        transform_params: "$(find upright_cmd)/config/robots/calibration/tray_transforms_real.yaml"
    tool_link_name: "gripped_object"
    base_type: fixed

  # weights on state, input, and end effector pose
  weights:
    input:
      scale: 0.001
      diag: [1rep6]
    state:
      scale: 0.01
      diag: [0rep6, 10rep6, 1rep6]
    end_effector:
      scale: 1
      diag: [1, 1, 1, 0, 0, 0]

  # state and input limits
  limits:
    constraint_type: hard
    input:
      lower: [-80, -80, -80, -80, -80, -80]
      upper: [80, 80, 80, 80, 80, 80]
    state:
      lower: [-2pi, -2pi, -2pi, -2pi, -2pi, -2pi,
              -2, -2, -3, -3, -3, -3,
              -10, -10, -10, -10, -10, -10]
      upper: [2pi, 2pi, 2pi, 2pi, 2pi, 2pi,
              2, 2, 3, 3, 3, 3,
              10, 10, 10, 10, 10, 10]
