# TODO: the Ridgeback-only simulation does not appear to be working correctly
# at the moment - possibly an issue with the locked joint implementation?
include:
  -
    key: simulation
    package: upright_cmd
    path: config/simulation.yaml
  -
    key: controller
    package: upright_cmd
    path: config/controller.yaml
  -
    package: upright_cmd
    path: config/robots/ridgeback.yaml

logging:
  timestep: 0.010
  log_dir: /media/adam/Data/PhD/Data/upright/bounded

simulation:
  duration: 10.0
  arrangement: pink_bottle

controller:
  balancing:
    enabled: true
    use_force_constraints: true
    arrangement: pink_bottle
    constraint_type: hard

  waypoints:
    -
      time: 0
      position: [2.0, 0, 0]
      orientation: [0, 0, 0, 1]
