# contains different home positions for use with the home.py script
# best practice is to make your own config file for home positions and tell
# the home.py script about it using the --config argument

#todo 需要从真机上面呢查看实际的home位置，有一个action home
default: [0, 0, 0, 1.5708, -0.7854,  1.5708, -0.7854,  1.5708, 1.3100]


# configuration used for projectile experiments
projectile2: [-1.5, 2.5, -1.5708, 1.5708, -0.7854,  1.5708, -0.7854,  1.5708, 1.3100]